---
repos:
- repo: https://github.com/ambv/black
  rev: 21.9b0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150']
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v2.4.1
  hooks:
  - id: prettier
    types_or: [html, markdown]
