"""Add Asset

Revision ID: 5233a83a785b
Revises: 63b6fa54d77c
Create Date: 2022-07-02 21:33:42.963275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5233a83a785b"
down_revision = "63b6fa54d77c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("asset")
    # ### end Alembic commands ###
