"""Lift

Revision ID: 63b6fa54d77c
Revises: f84cf65d4364
Create Date: 2021-09-26 15:42:37.425779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63b6fa54d77c"
down_revision = "f84cf65d4364"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lift",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["station.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lift")
    # ### end Alembic commands ###
