"""Updates

Revision ID: f84cf65d4364
Revises: 41fb2961c584
Create Date: 2021-09-25 23:09:20.942301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84cf65d4364'
down_revision = '41fb2961c584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('updates',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updates')
    # ### end Alembic commands ###
